### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by Bear67** [Angel-125/MCM#10]
If we download the 0.4.7 release which is 6 months old but your latest build is 3 months old. The MCM.version points to the DSEV release built for version 0.90.
![screenshot_9](https://cloud.githubusercontent.com/assets/5138687/10244030/325cb2ac-68c2-11e5-9758-40f5cb4b3304.jpg)
Can you push a KSP 1.0.4 Release out? Thanks,

**Comment by Angel-125** [comment]
MCM has actually been discontinued. Pathfinder is its successor. :)

**Comment by Bear67** [comment]
Any plans on keeping the Skydock250 & Skydock375 from MCM alive? Their the only two things I'm using from MCM.

**Comment by Angel-125** [comment]
Yes, absolutely. Once the ground elements of Pathfinder are done, I'll start on the orbital elements, and the Skydocks will be coming to Pathfinder. :)
